repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
        # YAML 文件语法检查（只检查，不修复）
      - id: check-json
        # JSON 文件语法检查
      - id: check-xml
        # XML 文件语法检查
      - id: check-merge-conflict
        # 检查合并冲突标记

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.1
    hooks:
      - id: forbid-tabs
        # 检查是否使用了制表符而不是空格
      - id: remove-tabs
        # 移除制表符（如果需要修复）

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: python -m pytest
        language: system
        pass_filenames: false
        always_run: true