repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-xml
      - id: check-merge-conflict

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.1
    hooks:
      - id: forbid-tabs
        exclude: "\.md$"  # 跳过 .md 文件
      - id: remove-tabs
        exclude: "\.md$"  # 跳过 .md 文件

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: python -m pytest
        language: system
        pass_filenames: false
        always_run: true